//ids are going to be generated by the database

export const posts = [
    {
        id: '1', 
        userId: '1',
        title: 'blah',
        body: 'blah',
        userName: 'Jack Miller',
        userTitle: 'Professor',
        likes: 5,
        dislikes: 5,
        credibilityVotes: 3,
        uncredibleVotes: 0,
        timeStamp: 'timestamp',
        commentIds: [
            '1'
        ]
    },
    {
        id: '2', 
        userId: '2',
        title: 'blah',
        body: 'blah',
        userName: 'Linda Dawn',
        userTitle: 'Scientist',
        likes: 5,
        dislikes: 5,
        credibilityVotes: 3,
        uncredibleVotes: 0,
        timeStamp: 'timestamp',
        commentIds: []
    },
]

export const users = [
    {
        id: '1', 
        name: 'Jack Miller',
        title: 'Professor',
        email: 'jackmiller@gmail.com',
        password: 'passauth',
        imageId: '230948293',
    },
    {
        id: '2', 
        name: 'Linda Dawn',
        title: 'Scientist',
        email: 'lindadawn@gmail.com',
        password: 'passauth',
        imageId: '398472394',
    },
]

export const comments = [
    {
        id: '1',
        postId: '1',
        userName: 'Linda Dawn',
        userTitle: 'Scientist',
        userImageId: '398472394',
        text: 'a comment'
    }
]